---

name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TWITTER_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
          TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}
        run: |
          mkdir -p ${HOME}/.ssh
          printf "%s\n" "$KNOWN_HOSTS" > ${HOME}/.ssh/known_hosts
          printf "%s\n" "$DEPLOY_KEY" > ${HOME}/.ssh/id_ed25519
          chmod 600 ${HOME}/.ssh/id_ed25519
          rsync -a ./ alain@deb2.afpy.org:/home/alain/src/
          ssh alain@deb2.afpy.org '
            /home/alain/venv/bin/python -m pip install --upgrade pip;
            /home/alain/venv/bin/python -m pip install --upgrade /home/alain/src/;
            sudo systemctl restart alain.service'
